input:
  address: datasets/car.data
  format: csv
  missing_values:
    - none
  headers: false

parsing:
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal

training:
  strategy: kx2-folds
  label_index: 6
  evaluation: classification-score
  model:
    name: knn-condensed
  partitioning: 
    strategy: stratified-kfold
    parameters:
      num_folds: 10
