input:
  address: datasets/car.data
  format: csv
  missing_values:
    - none
  headers: false

parsing:
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal
  - ordinal

training:
  strategy: kx2-folds
  label_index: 6
  evaluation: classification-score
  model:
    name: knn-condensed
    task: classification
    tuning:
      num_neighbors: [1, 2, 4, 8, 16, 32]
  partitioning: 
    strategy: stratified-kfold
    parameters:
      num_folds: 10
