input:
  address: datasets/machine.data
  format: csv
  missing_values:
    - "None"
  headers: false

parsing:
  - ordinal
  - ordinal
  - numeric
  - numeric
  - numeric
  - numeric
  - numeric
  - numeric
  - numeric
  - "null"

scrub:
  - name: mode
    index: 0
  - name: mode
    index: 1
  - name: mode
    index: 2
  - name: mode
    index: 3
  - name: mode
    index: 4
  - name: mode
    index: 5
  - name: mode
    index: 6
  - name: mode
    index: 7

training:
  label_index: 8
  evaluation: classification-score
  model:
    name: null-classifier
  validation: 
    strategy: kfold
    parameters:
      num_folds: 10
