input:
  address: datasets/iris/iris.data
  format: csv
  missing_values:
    - none
  headers: true

parsing:
  - numeric
  - numeric
  - numeric
  - numeric
  - nominal

training:
  label_index: 4
  evaluation: classification-score
  model:
    name: null-classifier
  validation: 
    strategy: stratified-kfold
    parameters:
      num_folds: 10
