input:
  address: datasets/iris/iris.data
  format: csv
  missing_values:
    - None
  headers: false

parsing:
  - numeric
  - numeric
  - numeric
  - numeric
  - nominal

training:
  label_index: 4
  evaluation: classification-score
  model:
    name: knn-edited
    parameters:
      epsilon: 0.001
  validation: 
    strategy: stratified-kfold
    parameters:
      num_folds: 10
