input:
  address: datasets/test.csv
  format: csv
  missing_values:
    - none
  headers: true

parsing:
  - ordinal
  - ordinal
  - ordinal

scrub:
  - name: mean
    index: 2

transform:
  - name: equal-width-discretization
    index: 0
    parameters:
      num_bins: 2
  - name: zscore
    index: 1

model:
  name: null-classifier
  validation: 
    strategy: kfold-stratified
    parameters:
      num_folds: 10
  evaluation: mse
