input:
  address: datasets/iris/iris.data
  format: csv
  missing_values:
    - None
  headers: false

parsing:
  - numeric
  - numeric
  - numeric
  - numeric
  - ordinal

training:
  strategy: kx2-folds
  label_index: 4
  model:
    name: knn-condensed
    parameters:
      epsilon: 0.01
  partitioning: 
    strategy: stratified-kfold
    parameters:
      num_folds: 10
  evaluation: classification-score
