input:
  address: datasets/test.csv
  format: csv
  missing_values:
    - none
  headers: true

parsing:
  - ordinal
  - ordinal
  - numeric

scrub:
  - name: mean
    index: 2

transform:
  - name: zscore
    index: 2

training:
  label_index: 2
  evaluation: mse
  model:
    name: null-classifier
  validation: 
    strategy: stratified-kfold
    parameters:
      num_folds: 2
